#!/usr/bin/env bash
# Generate converted.sql from a restored Ruby legacy database.
#
# Usage:
#   ./generate_converted_sql.sh --config build/dev/config.yaml \
#       --dump max_shizoid_production_20260607_143215.dump
#
# Apply to an empty Go database (goose migrations already run):
#   psql -h ... -U ... -d shizoid -v ON_ERROR_STOP=1 -f scripts/converted.sql
#
# Requires: pg_restore, createdb, dropdb, psql

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LEGACY_DB="${LEGACY_DB:-shizoid_legacy}"
OUT="${OUT:-$ROOT/scripts/converted.sql}"
CONFIG=""
DUMP=""
SKIP_RESTORE=0
LEGACY_DSN=""

usage() {
  sed -n '2,12p' "$0" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG="$2"; shift 2 ;;
    --dump) DUMP="$2"; shift 2 ;;
    --legacy-db) LEGACY_DB="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --skip-restore) SKIP_RESTORE=1; shift ;;
    --legacy-dsn) LEGACY_DSN="$2"; SKIP_RESTORE=1; shift 2 ;;
    -h|--help) usage ;;
    *) echo "unknown arg: $1" >&2; usage ;;
  esac
done

parse_yaml_db() {
  local file="$1"
  python3 - "$file" <<'PY'
import sys

section = None
values = {}
for raw in open(sys.argv[1], encoding="utf-8"):
    line = raw.rstrip()
    if not line or line.lstrip().startswith("#"):
        continue
    if line.endswith(":") and not line.startswith(" "):
        section = line[:-1]
        continue
    if section != "database" or ":" not in line:
        continue
    key, val = line.strip().split(":", 1)
    values[key] = val.strip().strip('"').strip("'")

host = values.get("host", "localhost")
if host in {"postgres", "db", "postgresql"}:
    host = "127.0.0.1"
print(host)
print(values.get("port", "5432"))
print(values.get("user", "shizoid"))
print(values.get("password", ""))
PY
}

if [[ -n "$CONFIG" ]]; then
  mapfile -t DB < <(parse_yaml_db "$CONFIG")
  DB_HOST="${DB[0]}"
  DB_PORT="${DB[1]}"
  DB_USER="${DB[2]}"
  DB_PASS="${DB[3]}"
else
  DB_HOST="${DB_HOST:-127.0.0.1}"
  DB_PORT="${DB_PORT:-5432}"
  DB_USER="${DB_USER:-shizoid}"
  DB_PASS="${DB_PASS:-}"
fi

export PGPASSWORD="$DB_PASS"
PSQL=(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -v ON_ERROR_STOP=1)

if [[ -z "$LEGACY_DSN" ]]; then
  LEGACY_DSN="host=$DB_HOST port=$DB_PORT user=$DB_USER password=$DB_PASS dbname=$LEGACY_DB"
fi

if [[ "$SKIP_RESTORE" -eq 0 ]]; then
  [[ -n "$DUMP" ]] || { echo "--dump is required unless --skip-restore" >&2; exit 1; }
  [[ -f "$DUMP" ]] || { echo "dump not found: $DUMP" >&2; exit 1; }
  echo "restoring dump into $LEGACY_DB..."
  dropdb --if-exists -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$LEGACY_DB"
  createdb -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" "$LEGACY_DB"
  pg_restore --no-owner --no-acl \
    -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" \
    -d "$LEGACY_DB" "$DUMP"
fi

emit_copy() {
  local label="$1"
  local table="$2"
  local columns="$3"
  local query="$4"

  echo "-- $label"
  echo "COPY $table ($columns) FROM stdin;"
  psql "$LEGACY_DSN" -v ON_ERROR_STOP=1 -c "COPY ($query) TO STDOUT"
  echo '\.'
  echo
}

mkdir -p "$(dirname "$OUT")"
echo "writing $OUT ..."

{
  cat <<'HEADER'
-- Generated by generate_converted_sql.sh
-- Apply to an empty Go database (goose migrations already applied).
-- Bayan / data_banks corpus pairs are skipped; duplicate words are merged.

BEGIN;
SET LOCAL synchronous_commit = off;

HEADER

  emit_copy "words (deduplicated)" "words" "id, word" \
    "SELECT DISTINCT ON (word) id, word FROM words ORDER BY word, id"

  emit_copy "chats" "chats" \
    "id, kind, random, eightball, greeting, winner, locale, generation_mode, title, first_name, last_name, username, active_at, created_at" \
    "SELECT c.telegram_id AS id, c.kind, c.random, c.eightball, c.greeting, c.winner, c.locale, 0::smallint AS generation_mode, c.title, c.first_name, c.last_name, c.username, c.active_at, c.created_at FROM chats c"

  emit_copy "users" "users" \
    "id, is_bot, first_name, last_name, username, language_code, captcha_solved_at, created_at, updated_at" \
    "SELECT id, is_bot, first_name, last_name, username, language_code, NULL::timestamptz AS captcha_solved_at, created_at, updated_at FROM users"

  emit_copy "participations" "participations" \
    "id, chat_id, user_id, score, active_at, left_at, created_at, updated_at" \
    "SELECT p.id, c.telegram_id AS chat_id, p.user_id, p.score, p.active_at, CASE WHEN p.\"left\" THEN COALESCE(p.active_at, p.updated_at) END AS left_at, p.created_at, p.updated_at FROM participations p JOIN chats c ON c.id = p.chat_id"

  emit_copy "pairs (deduplicated)" "pairs" "id, chat_id, first_id, second_id" \
    "WITH word_map AS (SELECT id AS old_id, MIN(id) OVER (PARTITION BY word) AS new_id FROM words) SELECT DISTINCT ON (c.telegram_id, f1.new_id, f2.new_id) p.id, c.telegram_id AS chat_id, f1.new_id AS first_id, f2.new_id AS second_id FROM pairs p JOIN chats c ON c.id = p.chat_id JOIN word_map f1 ON f1.old_id = p.first_id JOIN word_map f2 ON f2.old_id = p.second_id WHERE p.data_bank_id IS NULL ORDER BY c.telegram_id, f1.new_id, f2.new_id, p.id"

  emit_copy "replies (aggregated)" "replies" "pair_id, word_id, count" \
    "WITH word_map AS (SELECT id AS old_id, MIN(id) OVER (PARTITION BY word) AS new_id FROM words), pair_map AS (SELECT p.id AS old_id, FIRST_VALUE(p.id) OVER (PARTITION BY c.telegram_id, f1.new_id, f2.new_id ORDER BY p.id) AS new_id FROM pairs p JOIN chats c ON c.id = p.chat_id JOIN word_map f1 ON f1.old_id = p.first_id JOIN word_map f2 ON f2.old_id = p.second_id WHERE p.data_bank_id IS NULL) SELECT pm.new_id AS pair_id, wm.new_id AS word_id, SUM(r.count) AS count FROM replies r JOIN pairs p ON p.id = r.pair_id AND p.data_bank_id IS NULL JOIN pair_map pm ON pm.old_id = r.pair_id LEFT JOIN word_map wm ON wm.old_id = r.word_id GROUP BY pm.new_id, wm.new_id"

  emit_copy "winners" "winners" "id, chat_id, user_id, date, created_at" \
    "SELECT w.id, c.telegram_id AS chat_id, w.user_id, w.date, w.created_at::timestamptz AS created_at FROM winners w JOIN chats c ON c.id = w.chat_id"

  emit_copy "greetings" "greetings" "id, chat_id, text" \
    "SELECT g.id, c.telegram_id AS chat_id, g.text FROM greetings g JOIN chats c ON c.id = g.chat_id"

  cat <<'FOOTER'
SELECT setval('words_id_seq',          (SELECT COALESCE(MAX(id), 1) FROM words));
SELECT setval('pairs_id_seq',          (SELECT COALESCE(MAX(id), 1) FROM pairs));
SELECT setval('replies_id_seq',        (SELECT COALESCE(MAX(id), 1) FROM replies));
SELECT setval('participations_id_seq', (SELECT COALESCE(MAX(id), 1) FROM participations));
SELECT setval('winners_id_seq',        (SELECT COALESCE(MAX(id), 1) FROM winners));
SELECT setval('greetings_id_seq',      (SELECT COALESCE(MAX(id), 1) FROM greetings));

COMMIT;
FOOTER

} > "$OUT"

ls -lh "$OUT"
echo "done"
